# Generated by Django 4.0.5 on 2022-07-04 15:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aluno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=194, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=194, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('endereco', models.CharField(max_length=194, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'aluno',
                'verbose_name_plural': 'alunos',
                'db_table': 'aluno',
            },
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=194, verbose_name='Nome de Curso')),
                ('ativo', models.BooleanField(verbose_name='Ativo')),
                ('data_inicio', models.DateField(verbose_name='Data de Início')),
                ('data_termino', models.DateField(verbose_name='Data de Término')),
            ],
            options={
                'verbose_name': 'curso',
                'verbose_name_plural': 'cursos',
                'db_table': 'curso',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_menu', models.CharField(max_length=50, verbose_name='Opção visível no menu')),
                ('caminho', models.CharField(max_length=194, verbose_name='Caminho')),
            ],
            options={
                'verbose_name': 'menu',
                'verbose_name_plural': 'menus',
                'db_table': 'menu',
            },
        ),
        migrations.CreateModel(
            name='Telefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'telefone',
                'verbose_name_plural': 'telefones',
                'db_table': 'telefone',
            },
        ),
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=194, verbose_name='Nome')),
                ('sobrenome', models.CharField(max_length=194, verbose_name='Sobrenome')),
                ('email', models.EmailField(max_length=254, verbose_name='E-mail')),
                ('estado', models.CharField(max_length=2, verbose_name='Estado')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('endereco', models.CharField(max_length=194, verbose_name='Endereço')),
                ('telefoneID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escolar.telefone', verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'professor',
                'verbose_name_plural': 'professores',
                'db_table': 'professor',
            },
        ),
        migrations.CreateModel(
            name='LkeDeslike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.PositiveIntegerField(verbose_name='Like')),
                ('deslike', models.PositiveIntegerField(verbose_name='DesLike')),
                ('alunoID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escolar.aluno', verbose_name='Aluno')),
                ('cursoID', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escolar.curso', verbose_name='Curso')),
            ],
            options={
                'verbose_name': 'likedeslike',
                'verbose_name_plural': 'likedeslikes',
                'db_table': 'likedeslike',
            },
        ),
        migrations.AddField(
            model_name='curso',
            name='professorID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escolar.professor', verbose_name='Professor'),
        ),
        migrations.AddField(
            model_name='aluno',
            name='telefoneID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='escolar.telefone', verbose_name='Telefone'),
        ),
    ]
