# Generated by Django 4.0.5 on 2022-07-05 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolar', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aluno',
            name='telefoneID',
            field=models.ForeignKey(db_column='telefoneID', on_delete=django.db.models.deletion.PROTECT, to='escolar.telefone', verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='professorID',
            field=models.ForeignKey(db_column='professorID', on_delete=django.db.models.deletion.PROTECT, to='escolar.professor', verbose_name='Professor'),
        ),
        migrations.AlterField(
            model_name='lkedeslike',
            name='alunoID',
            field=models.ForeignKey(db_column='alunoID', on_delete=django.db.models.deletion.PROTECT, to='escolar.aluno', verbose_name='Aluno'),
        ),
        migrations.AlterField(
            model_name='lkedeslike',
            name='cursoID',
            field=models.ForeignKey(db_column='cursoID', on_delete=django.db.models.deletion.PROTECT, to='escolar.curso', verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='telefoneID',
            field=models.ForeignKey(db_column='telefoneID', on_delete=django.db.models.deletion.PROTECT, to='escolar.telefone', verbose_name='Telefone'),
        ),
    ]
