# Generated by Django 4.0.5 on 2022-07-07 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolar', '0002_alter_aluno_telefoneid_alter_curso_professorid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelefoneProfessor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=11, verbose_name='Telefone')),
            ],
            options={
                'verbose_name': 'telefone_professor',
                'verbose_name_plural': 'telefones_profeesores',
                'db_table': 'telefone_professor',
            },
        ),
        migrations.RemoveField(
            model_name='aluno',
            name='telefoneID',
        ),
        migrations.RemoveField(
            model_name='professor',
            name='telefoneID',
        ),
        migrations.AddField(
            model_name='professor',
            name='usuarioID',
            field=models.BigIntegerField(blank=True, db_column='usuarioID', null=True),
        ),
        migrations.AlterField(
            model_name='professor',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.DeleteModel(
            name='Telefone',
        ),
        migrations.AddField(
            model_name='telefoneprofessor',
            name='professorID',
            field=models.ForeignKey(db_column='professorID', on_delete=django.db.models.deletion.PROTECT, to='escolar.professor', verbose_name='Professor'),
        ),
    ]
