# Generated by Django 4.0.5 on 2022-07-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolar', '0004_telefonealuno'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(max_length=194, verbose_name='Tipo de Usuário')),
                ('is_professor', models.BooleanField(default=False)),
                ('is_aluno', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'tipo_usuario',
                'verbose_name_plural': 'tipos_usuarios',
                'db_table': 'tipo_usuario',
            },
        ),
    ]
