# Generated by Django 4.0.5 on 2022-07-11 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolar', '0005_tipousuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='tipousuario',
            name='usuario_id',
            field=models.IntegerField(db_column='usuario_id', default=0),
        ),
    ]
