# Generated by Django 4.0.5 on 2022-07-12 02:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolar', '0007_remove_tipousuario_usuario_id_tipousuario_usuarioid'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssociarMenuUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_staff', models.BooleanField(default=False)),
                ('opcao_menuID', models.ForeignKey(db_column='opcao_menuID', on_delete=django.db.models.deletion.PROTECT, to='escolar.menu', verbose_name='Opção visível no menu')),
                ('tipo_usuarioID', models.ForeignKey(db_column='tipo_usuarioID', on_delete=django.db.models.deletion.PROTECT, to='escolar.tipousuario', verbose_name='Tipo de usuário: Aluno/Professor')),
            ],
            options={
                'verbose_name': 'associar_menu_usuario',
                'verbose_name_plural': 'associar_menu_usuarios',
                'db_table': 'associar_menu_usuario',
            },
        ),
    ]
