# Generated by Django 4.0.5 on 2022-07-12 05:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolar', '0008_associarmenuusuario'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='associarmenuusuario',
            name='opcao_menuID',
        ),
        migrations.AddField(
            model_name='associarmenuusuario',
            name='menuID',
            field=models.ForeignKey(db_column='menuID', default=0, on_delete=django.db.models.deletion.PROTECT, to='escolar.menu', verbose_name='Opção visível no menu'),
        ),
    ]
