# Generated by Django 4.0.5 on 2022-07-12 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolar', '0009_remove_associarmenuusuario_opcao_menuid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissaoMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuID', models.BigIntegerField(db_column='menuID', verbose_name='Opção no menu')),
                ('is_membro_staff', models.BooleanField(default=False)),
                ('tipo_usuarioID', models.ForeignKey(db_column='tipo_usuarioID', on_delete=django.db.models.deletion.PROTECT, to='escolar.tipousuario', verbose_name='Tipo de usuário: Aluno/Professor')),
            ],
            options={
                'verbose_name': 'permissao_menu',
                'verbose_name_plural': 'permissao_menus',
                'db_table': 'permissao_menu',
            },
        ),
    ]
