# Generated by Django 4.0.5 on 2022-07-12 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolar', '0010_permissaomenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tipocolaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_colaborador', models.CharField(max_length=194, verbose_name='Tipo de colaborador')),
            ],
            options={
                'verbose_name': 'tipo_colaborador',
                'verbose_name_plural': 'tipo_colaboradores',
                'db_table': 'tipo_colaborador',
            },
        ),
        migrations.AlterModelOptions(
            name='tipousuario',
            options={'verbose_name': 'tipo_usuario_cadastrado', 'verbose_name_plural': 'tipo_usuario_cadastrados'},
        ),
        migrations.AlterModelTable(
            name='tipousuario',
            table='tipo_usuario_cadastrado',
        ),
        migrations.DeleteModel(
            name='PermissaoMenu',
        ),
        migrations.AlterField(
            model_name='associarmenuusuario',
            name='tipo_usuarioID',
            field=models.ForeignKey(db_column='tipo_usuarioID', on_delete=django.db.models.deletion.PROTECT, to='escolar.tipocolaborador', verbose_name='Tipo de usuário: Aluno/Professor'),
        ),
    ]
