# Generated by Django 4.0.5 on 2022-07-12 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escolar', '0013_alter_associarmenuusuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipousuario',
            options={'verbose_name': 'tipo_usuario', 'verbose_name_plural': 'tipo_usuarios'},
        ),
        migrations.AlterModelTable(
            name='tipousuario',
            table='tipo_usuario',
        ),
    ]
