# Generated by Django 4.0.5 on 2022-07-12 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolar', '0014_alter_tipousuario_options_alter_tipousuario_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associarmenuusuario',
            name='tipo_usuario',
            field=models.CharField(choices=[('Professor', 'Professor'), ('Aluno', 'Aluno')], db_column='tipo_usuario', default='', max_length=194, verbose_name='Tipo de usuário: Aluno/Professor'),
        ),
    ]
