# Generated by Django 4.0.5 on 2022-07-13 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escolar', '0015_alter_associarmenuusuario_tipo_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tipousuario',
            name='usuarioID',
            field=models.IntegerField(db_column='usuario_id', default=0),
        ),
    ]
