# Generated by Django 4.0.5 on 2022-07-13 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('escolar', '0016_alter_tipousuario_usuarioid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='associarmenuusuario',
            name='menuID',
            field=models.ForeignKey(db_column='menu_id', default=0, on_delete=django.db.models.deletion.PROTECT, to='escolar.menu', verbose_name='Opção visível no menu'),
        ),
    ]
