# Generated by Django 4.0.5 on 2022-07-07 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'managed': False, 'verbose_name': 'usuario', 'verbose_name_plural': 'usuarios'},
        ),
    ]
